import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_components/theme-provider";
import { Toaster } from "~/components/ui/toaster";
import AuthProvider from "~/AuthProvider";
import RouteChangeHandler from "./_components/RouteChangeHandler";

export const metadata: Metadata = {
  title: "Gallery Studio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo-white.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <RouteChangeHandler />
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster />

          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
